MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: './models/resnet50-19c8e357.pth'
  KEEP_CAMID_CENTROIDS: True

DATASETS:
  LABELED: True

INPUT:
  SIZE_TRAIN: [384,128]
  SIZE_TEST: [384,128]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 3.5e-4
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 20
  USE_SUPERVISED_CONTRASTIVE_LOSS : True
  SUPERVISED_CONTRASTIVE_LOSS_WEIGHT: 0.1

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 1